export const ADD_TO_CURRENCIES = "ADD_TO_CURRENCIES";
export const ADD_TO_CODES = "ADD_TO_CODES";
export const ADD_TO_CURRENCY = "ADD_TO_CURRENCY";
export const ADD_TO_CURRENCY_COUNTRY = "ADD_TO_CURRENCY_COUNTRY";
export const ADD_TO_TIME_COUNTRY = "ADD_TO_TIME_COUNTRY";
export const ADD_TO_TIMES = "ADD_TO_TIMES";
export const ADD_TO_TIME = "ADD_TO_TIME";
export const LOAD_CURRENCY = "LOAD_CURRENCY";
export const LOAD_COUNTRIES = "LOAD_COUNTRIES";
export const LOAD_CURRENCY_CODES = "LOAD_CURRENCY_CODES";

